// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tyjlodscrvryxtonsxuu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR5amxvZHNjcnZyeXh0b25zeHV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMDAyMzgsImV4cCI6MjA2MzU3NjIzOH0.EK41mm73Y0wjaB2oU4GA-sGbiO79EJ8dPnyruGYOsFA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);